module.exports = {
    userNotExist: 'User doesn\'t exist',
    userAlreadyExist: 'User already exist',
    userIsNotMature: 'User is not mature enough to add property',
    requiredFieldsEmpty: 'One or more of the required are empty',
    passwordNotMatching: 'Passwords do not match',
    passwordLengthNotEnough: 'Password should be at least 6 characters',
    userNotVerified: 'USer has not yet verified his/her email address. Please verify your email.',
    emailNotSent: 'Problem sending verification email',
    errorSavingUser: 'Problem saving new user to DataBase',
    errorSavingUserInfo: 'Problem saving user info to DataBase',
    errorUpdatingUser: 'Problem updating User to DataBase',
    errorUpdatingProp: 'Problem updating property to DataBase',
    userNotRegistered: 'This email address is not registered.',
    extraInfoAlreadyGiven: 'User already gave extra information',
    propNotFound: 'Property not found.',
    problemFatchingProps: 'Problem Fatching Properties.',
    propAlreadyExist: 'Property already in wishlist',
    someThingWentWrong: 'Some thing went wrong'
};
